parallel-jobs = 4
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "revanced/revanced-cli"
rv-brand = "ReVanced Extended"

[YouTube]
build-mode = "module"
excluded-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube' 'Enable debug logging'"
included-patches = "'MaterialYou'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"

[YTMusic]
build-mode = "module"
app-name = "Music"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding Music name' 'Enable compact dialog' 'Enable debug logging'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrvx-magisk"
arch = "arm64-v8a"
