name: GitHub Cleanup

on:
  workflow_dispatch:
    inputs:
      CLEANUP:
        description: 'Clear GitHub'
        required: false
        type: boolean
        default: true

jobs:
  cleanup:
    name: GitHub Cleanup
    if: ${{ inputs.CLEANUP }}
    uses: nikhilbadyal/ghactions/.github/workflows/github-cleanup.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
